### PR TITLE
Updated links

### PR DESCRIPTION
**Pull request by nek7u**
**1. Fixed broken links.**
<details><summary>Details:</summary>

<p><br></p>
https://dead-link-checker.com/en/

```
1:
https://docs.rainmeter.net/manual/@vault-folder/ can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/history/

2:
https://docs.rainmeter.net/manual/plugins/virtualdesktops/ can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/history/

3:
https://docs.rainmeter.net/manual/user-interface/manage/%20 can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/manual/settings/skin-sections/
https://docs.rainmeter.net/manual/skins/rainmeter-section/defaults/

4:
https://docs.rainmeter.net/manual/manage/ can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/manual/skins/rainmeter-section/defaults/

5:
https://docs.rainmeter.net/manual/getting-started/basic-tutorials/system/!meters/roundline can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/manual/getting-started/basic-tutorials/system/

6:
https://docs.rainmeter.net/measures/general-options/ can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/manual/measures/memory/

7:
https://docs.rainmeter.net/manual/meters/histogram/MeasureName can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/manual/meters/histogram/

8:
https://docs.rainmeter.net/manual/plugins/audiolevel/RMSOptions can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/manual/plugins/audiolevel/

9:
https://docs.rainmeter.net/tips/skins/option-types/ can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/tips/webparser-tutorial/

10:
https://docs.rainmeter.net/tips/img/wrapping-text%5Cwrapping-text.jpg can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/tips/wrapping-text/

11:
https://opensource.org/licenses/MIT can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/manual/distributing-skins/

12:
http://luacurl.luaforge.net/ can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/manual/lua-scripting/

13:
https://github.com/google/material-design-icons/tree/master/iconfont can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/manual/variables/character-variables/

14:
https://www.hwinfo.com/ can not be accessed.
This URL is linked by these url.
https://docs.rainmeter.net/tips/hwinfo/
```

No.11 and No.14 was due to temporary issues and the url links looked fine.
</details>

**2. Changed from `http://` to `https://`**  
<details><summary>Exceptions:</summary>

<p><br></p>

```md
#### Page does not exist. (also I couldn't find out an alternative page)

* source\history.html
Line 2265: <a href="http://support.microsoft.com/kb/282187">msdn.microsoft.com</a>

* source\developers\index.html
Line 46: <a href="http://www.certum.pl/certum/main.xml">service</a>

* source\manual\getting-started\customizing.html
Line 19: <a href="http://lifehacker.com/rainmeter/">Lifehacker</a>
Line 20: <a href="http://lifehacker.com/rainmeter/">Rainmeter tag</a>

* source\manual\measures\nowplaying.html
Line 72: <em>http://lyrics.wikia.com</em>

* source\manual\measures\time.html
Line 126: <a href="http://www.microsoft.com/en-us/download/details.aspx?id=25241">Microsoft National Language Support Downlevel APIs 1.0</a>

* source\snippets\autoscale.html
Line 6: <a href="http://www.t1shopper.com/tools/calculate/">More information</a>

* source\tips\notepad-alternatives.html
Line 62: <a href="http://windows.microsoft.com/en-US/windows7/Change-the-program-that-opens-a-type-of-file">associate</a>



#### HTTPS is unavailable or SSL Certificate is invalid.

* source\history.html
Line 1165: <a href="http://www.blooberry.com/indexdot/html/topics/urlencoding.htm">URL-encoded</a>

* source\manual\lua-scripting\index.html
Line 14: <a href="http://lua-users.org/wiki/LuaTutorial">Lua Tutorial</a>

* source\manual\measures\webparser.html
Line 71: <a href="http://www.blooberry.com/indexdot/html/topics/urlencoding.htm">URL-Encode</a>

* source\manual\variables\section-variables.html
Line 108: <a href="http://www.blooberry.com/indexdot/html/topics/urlencoding.htm">URL-Encoded</a>

* source\snippets\read-write-file.html
Line 6: <a href="http://lua-users.org/wiki/IoLibraryTutorial">Io Library</a>
```

</details>

**3. Changed from `https://msdn.microsoft.com/...` to `https://docs.microsoft.com/...`**  
> [An Update on the MSDN and TechNet Migration to docs.microsoft.com](https://docs.microsoft.com/teamblog/msdn-technet-migration)

### CODE REVIEW

**Comment by nek7u** [comment]
**Deprecated HideOnMouseOver, replaced with OnHover**

**Version History**
> [March 24, 2022](https://docs.rainmeter.net/history/#r3632) - 4.5.13 - Revision 3632
> [Changed] Settings: Deprecated "HideOnMouseOver" and replaced with "OnHover" in Rainmeter.ini.

See Forum [[BUG] The new "OnHover" name breaks "DefaultHideOnMouseOver"](https://forum.rainmeter.net/viewtopic.php?t=41264)

**Comment by nek7u** [comment]
Please let me know, if I need to fix something.
I feel more explanation is needed in the following sentence.
[source/manual/measures/registry.html](https://github.com/rainmeter/rainmeter-docs/pull/28/commits/50c725f8bd17f12bab15dadb7a5e1e9f868288dd#diff-b8aff4247d07b76b21be779abe0f7c609c05781644e5727ead1ab559a8c561bcR44)
```html
<li><code>REG_BINARY</code> (string): Binary data in any form.</li>
```

**Comment by brianferguson** [comment]
Thank you for the PR! Unfortunately, I cannot accept it for a few reasons.

1. Instead of submitting a PR with lots of commits on different topics, please separate and submit a different PR for each topic. For example, submit the "http to https" commit(s) with their own PR.  You might not need more than 1 commit for all those changes (if possible). The "HideOnMouseOver" commits should be a separate PR as well.
**The goal is to "group" similar items for each PR. This makes it really easy to review. Also, the fewer the commits within the PR, the better.**
2. Updating the old "msdn" links is great, but the text might need to be modified as well. It looks like you did a really good job at this, but maybe a few slipped through. Example: https://github.com/nek7u/rainmeter-docs/commit/20150576ffb4e76c1ddf9e4d14d435c3d5c2111c
3. You may need to double check a few of the links, because some of them are still not correct. Example: https://github.com/nek7u/rainmeter-docs/commit/20150576ffb4e76c1ddf9e4d14d435c3d5c2111c (same link as item 2 above)
4. Adjust the FontAwesome links to their direct website, instead of the github link. This way, our link to their website will always show the most up to date version of their fonts, instead of us linking to a specific version and having to constantly update our link to their latest. This is probably what we should link to: [https://fontawesome.com/docs/desktop/setup/get-started](https://fontawesome.com/docs/desktop/setup/get-started)
5. Place the `REG_BINARY` stuff in its own PR.
6. It looks like a date for r3433 on the history is off by one day in your [PR](https://github.com/nek7u/rainmeter-docs/commit/90f24b844611e9de3a99b5097e4b23a4181c2038) (probably a typo). It should be [February 11](https://github.com/rainmeter/rainmeter/releases/tag/v4.4.0.3433), not 12. Thank you for finding this.

Also, thank you for all the time you put into this - especially the list of changes you made, and the list of links we need to look at.

-Brian

**Comment by nek7u** [comment]
Thank you for having the time to review my bad pull requests.
I need to learn more about a pull request and how to use GitHub.

Currently I don't have any tool for proper pull request, sometime I will understand about a PR, I might try it again.
(I have created the pull requests with Notepad++ and Web Browser, maybe I need a GitHub Desktop app or something.)

**Pull request closed without merging**
